export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh-token',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  PROFILE: {
    GET: '/users/profile',
    UPDATE: '/users/profile',
  },
  RESUMES: {
    LIST: '/resumes',
    UPLOAD: '/resumes',
    DETAILS: (id: string) => `/resumes/${id}`,
    UPDATE: (id: string) => `/resumes/${id}`,
    DELETE: (id: string) => `/resumes/${id}`,
  },
  JOBS: {
    LIST: '/jobs',
    CREATE: '/jobs',
    DETAILS: (id: string) => `/jobs/${id}`,
    UPDATE: (id: string) => `/jobs/${id}`,
    DELETE: (id: string) => `/jobs/${id}`,
    MATCH_RESUMES: (id: string) => `/jobs/${id}/match-resumes`,
  },
  APPLICATIONS: {
    LIST: '/applications',
    CREATE: '/applications',
    UPDATE_STATUS: (id: string) => `/applications/${id}/status`,
    DELETE: (id: string) => `/applications/${id}`,
  },
  REFERRALS: {
    LIST: '/referrals',
    CREATE: '/referrals',
    UPDATE_STATUS: (id: string) => `/referrals/${id}/status`,
    DELETE: (id: string) => `/referrals/${id}`,
    TEMPLATE: (id: string) => `/referrals/${id}/template`,
  },
  FOLLOWUPS: {
    LIST: '/followups',
    CREATE: '/followups',
    UPDATE_STATUS: (id: string) => `/followups/${id}/status`,
    DELETE: (id: string) => `/followups/${id}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    CREATE: '/notifications',
    MARK_ALL_READ: '/notifications/mark-all-read',
    DETAILS: (id: string) => `/notifications/${id}`,
    UPDATE: (id: string) => `/notifications/${id}`,
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    DELETE: (id: string) => `/notifications/${id}`,
  },
  DASHBOARD: {
    SUMMARY: '/dashboard/summary',
    RECENT_ACTIVITY: '/dashboard/recent-activity',
    UPCOMING_ACTIONS: '/dashboard/upcoming-actions',
  },
  ANALYTICS: {
    RESUMES: '/analytics/resumes',
    APPLICATIONS: '/analytics/applications',
    CONVERSIONS: '/analytics/conversions',
    SOURCES: '/analytics/sources',
  },
  AI: {
    TAILOR_RESUME: '/ai/resume',
    SAVE_TAILORED_RESUME: '/ai/resume/save',
    GENERATE_COVER_LETTER: '/ai/cover-letter',
    SAVE_COVER_LETTER: '/ai/cover-letter/save',
    GENERATE_REFERRAL: '/ai/referral-message',
    SKILL_GAP: '/ai/skill-gap',
  },
  COVER_LETTERS: {
    LIST: '/cover-letters',
    DETAILS: (id: string) => `/cover-letters/${id}`,
    DELETE: (id: string) => `/cover-letters/${id}`,
  },
} as const
